### ISSUE TITLE
Why is official documentation referenced to 404-page on github?

### ISSUE THREAD

**Issue by dimti** [holland-backup/holland-backup.github.io#8]
On this: https://hollandbackup.org

Then https://docs.hollandbackup.org/

Redirecto to

https://holland-backup.github.com/docs

And i got 404 error.

|||
|---|---|
|![image](https://user-images.githubusercontent.com/582144/116510615-da599c80-a8cd-11eb-9be7-2c21815102ca.png)|![image](https://user-images.githubusercontent.com/582144/116510632-e0e81400-a8cd-11eb-9e48-588b857f84fd.png)|

**Comment by soulen3** [comment]
Thanks for reporting this issue.  I missed the redirect in the index.html file. This should be fixed now.
